CREATE TABLE Categories(
  Id INT IDENTITY PRIMARY KEY,
  [Name] NVARCHAR(100) NOT NULL
);

CREATE TABLE Books(
  Id INT IDENTITY PRIMARY KEY,
  Title NVARCHAR(200) NOT NULL,
  Author NVARCHAR(200) NULL,
  PublishedOn DATE NULL
);

CREATE TABLE BookCategories(
  BookId INT NOT NULL FOREIGN KEY REFERENCES Books(Id) ON DELETE CASCADE,
  CategoryId INT NOT NULL FOREIGN KEY REFERENCES Categories(Id) ON DELETE CASCADE,
  CONSTRAINT PK_BookCategories PRIMARY KEY (BookId, CategoryId)
);
